config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "static_pages#home"
  get "static_pages/help"
  get "orders_active", to: "orders#active"

  resources :books
  resources :publishers
  resources :authors
  resources :carts
  resources :orders
  resources :line_items
  resources :users
  
  delete 'admin/users/:id' => 'admin/users#destroy', :via => :delete, :as => :admin_destroy_user
  delete 'admin/authors/:id' => 'admin/authors#destroy', :via => :delete, :as => :admin_destroy_author
  delete 'admin/publishers/:id' => 'admin/publishers#destroy', :via => :delete, :as => :admin_destroy_publisher
  delete 'admin/books/:id' => 'admin/books#destroy', :via => :delete, :as => :admin_destroy_book

  namespace :admin do
    resources :books
    resources :authors
    resources :publishers
    resources :users
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :author_books, dependent: :destroy
  has_many :authors, through: :author_books
  has_many :book_publishers, dependent: :destroy
  has_many :publishers, through: :book_publishers
  has_many :line_items

  accepts_nested_attributes_for :authors, :publishers, :author_books, :book_publishers

  validates :title, presence: true, length: { maximum: 100}
  validates :description, presence: true, length: { maximum: 1000 }
  validates :price, presence: true
  validates :role, presence: true
  enum role: { available: 0, unavailable: 1 }

  before_destroy :check_if_has_line_item

  mount_uploader :image, ImageUploader

  private

  def check_if_has_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'This book has a LineItem')
      return false
    end
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :get_book, only: [:show, :update, :destroy, :edit]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = "Book successfully created"
      redirect_to root_path
    else
      flash[:error] = "Something went wrong"
      render "new"
    end
  end

  def edit
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = "Book updated"
      redirect_to books_path
    else
      render 'edit'
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    flash[:success] = "Book deleted"
    redirect_to books_url
  end

  private

  def get_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :description, :price, :image, :user_id, :role, author_ids: [], publisher_ids: [],
      author_books_attributes: [:id, :book_id, :author_id],
      authors_attributes: [:id, :name, :country, :age],
      book_publishers_attributes: [:id, :book_id, :publisher_id],
      publishers_attributes: [:id, :name, :address]
    )
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @q = Book.ransack(params[:q])
    @books  =  @q.result.paginate(:page => params[:page], :per_page => 3)
    @cart = current_cart
  end

  def show
    if (Book.find_by id: params[:id]).nil?
      flash[:danger] = "Không Tồn Tại Sách!"
      redirect_to root_path
    else
      @book = Book.find_by id: params[:id]
      @authors = @book&.authors
      book_publishers = BookPublisher.find_by(book_id: @book.id)
      @publisher = book_publishers&.publisher
    end
  end
end

app/views/admin/books/edit.html.erb
<h2>Edit </h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3-edit-user">
    <%= form_for :book, url: {action: :update, controller: :books}, method: :put do |f| %>
      <h3 id="signup-form-admin">Update Author</h3>
      <%= f.label :title %><br />
      <%= f.text_field :title, class: "form-control" %>
      <%= f.label :description %><br />
      <%= f.text_field :description, class: "form-control" %>
      <%= f.label :price %><br />
      <%= f.number_field :price, class: "form-control" %>
      <%= f.file_field :image %>
      <%= f.label "Available" %>
      <%= f.radio_button(:role, "available") %>
      <%= f.label "Unavailable", class: "label_role" %>
      <%= f.radio_button(:role, "unavailable") %>
      <h2>Author</h2>
      <%= f.select :author_ids, options_for_select(Author.all.map {|author| [author.name, author.id]}), {}, multiple: true %>
      <%= link_to "Create author", new_admin_author_path , class: "btn btn-primary" %>
      <h2>Publisher</h2>
      <%= f.select :publisher_ids, options_for_select(Publisher.all.map {|publisher| [publisher.name, publisher.id]}), {}, multiple: true %>
      <%= link_to "Create publisher", new_admin_publisher_path , class: "btn btn-primary" %>
      <div class="form-group row">
        <div class="col-sm-10">
          <button type="submit" class="btn btn-primary">Update my book</button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/books/new.html.erb
<%provide(:title, "Create Book")%>
<h1>Create Book</h1>
<div class="row">
  <div class="form-group col-md-6">
    <%= form_for @book, url: admin_books_path, method: :post, :html => {:multipart => true} do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.label :title %><br />
      <%= f.text_field :title, class: "form-control" %>
      <%= f.label :description %><br />
      <%= f.text_field :description, class: "form-control" %>
      <%= f.label :price %><br />
      <%= f.number_field :price, class: "form-control" %>
      <%= f.file_field :image %>
      <%= f.label "Available" %>
      <%= f.radio_button(:role, "available") %>
      <%= f.label "Unavailable", class: "label_role" %>
      <%= f.radio_button(:role, "unavailable") %>
      <h2>Author</h2>
      <%= f.select :author_ids, options_for_select(Author.all.map {|author| [author.name, author.id]}), {}, multiple: true %>
      <%= link_to "Create author", new_admin_author_path , class: "btn btn-primary" %>
      <h2>Publisher</h2>
      <%= f.select :publisher_ids, options_for_select(Publisher.all.map {|publisher| [publisher.name, publisher.id]}), {}, multiple: true %>
      <%= link_to "Create publisher", new_admin_publisher_path , class: "btn btn-primary" %>
      <div class="form-group row">
        <div class="col-sm-10">
          <button type="submit" class="btn btn-primary">Create my book</button>
        </div>
      </div>
    <% end %>
  </div>
</div>